services:
  mssql:
    container_name: MSSQL
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    user: root
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql/data
    restart: always
    environment:
      MSSQL_SA_PASSWORD: Password0
      ACCEPT_EULA: Y

  mysql:
    container_name: MySQL
    image: mysql:8.0.36-bookworm
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password0

  ubuntu:
    container_name: Ubuntu-SSH
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu22.04-ssh
    ports:
      - 22:22
      - 80:80

volumes:
  mssql:
  mysql:
  ubuntu: