FROM ubuntu:22.04

RUN apt update && apt install  openssh-server sudo -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 ubuntu 

RUN  echo 'ubuntu:ubuntu' | chpasswd

RUN service ssh start

EXPOSE 22 80

CMD ["/usr/sbin/sshd","-D"]
